#!/usr/bin/env bash

echo "Generating docker-pull-output.rb cask file..."

VERSION="${VERSION:-${GITHUB_REF##*/}}"

SHA_DARWIN_ARM64="$(sha256sum artifacts/archives/docker-pull-output_darwin_arm64.tar.gz | awk '{print $1}')"
SHA_LINUX_AMD64="$(sha256sum artifacts/archives/docker-pull-output_linux_amd64.tar.gz | awk '{print $1}')"
SHA_LINUX_ARM64="$(sha256sum artifacts/archives/docker-pull-output_linux_arm64.tar.gz | awk '{print $1}')"

tee "docker-pull-output.rb" << EOF
# This file was generated by generate_homebrew_cask.sh. DO NOT EDIT.
cask "docker-pull-output" do
  name "docker-pull-output"
  desc "Docker Pull Output Parser"
  homepage "https://github.com/na4ma4/docker-pull-output"
  version "${VERSION}"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-pull-output"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/docker-pull-output/releases/download/v#{version}/docker-pull-output_darwin_arm64.tar.gz"
      sha256 "${SHA_DARWIN_ARM64}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/na4ma4/docker-pull-output/releases/download/v#{version}/docker-pull-output_linux_amd64.tar.gz"
      sha256 "${SHA_LINUX_AMD64}"
    end
    on_arm do
      url "https://github.com/na4ma4/docker-pull-output/releases/download/v#{version}/docker-pull-output_linux_arm64.tar.gz"
      sha256 "${SHA_LINUX_ARM64}"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docker-pull-output"]
    end
  end

  # No zap stanza required
end
EOF

echo "Generated docker-pull-output.rb"
