name: "CI"

on:
  pull_request:
  push:
    branches:
    - '**'
    tags:
    - '**'

jobs:
  unit-test:
    name: "Unit Test"
    uses: na4ma4/actions/.github/workflows/unit-test.yml@main
    secrets: inherit

  goreleaser:
    name: "Goreleaser"
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - unit-test
    uses: na4ma4/actions/.github/workflows/goreleaser.yml@main
    secrets:
      GO_RELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
