name: "Release"

on:
  push:
    tags:
    - '*'

goreleaser:
  name: "Goreleaser"
  if: startsWith(github.ref, 'refs/tags/v')
  uses: na4ma4/actions/.github/workflows/goreleaser.yml@main
  secrets:
    GO_RELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
